name: Debug build

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble Debug
        run: ./gradlew assembleDebug -PdisablePreDex -Pabi=${{ matrix.abi }}

