name: Publish release

on:
  release:
    types: published

env:
  ANDROID_SDK_TOOLS:  "6514223"
  ANDROID_NDK:        "21.2.6472646"
  ANDROID_CMAKE:      "3.10.2.4988404"

jobs:
  bintray:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: .github/installAndroidTools.sh

      - name: Download assets from this Release
        uses: ViliusSutkus89/release-asset-downloader@v1.0.3
        with:
          outputDirectory: 'releaseAssets'

      - name: Put release assets where gradle would have kept it after the build
        run: |
          ls -lha ./releaseAssets
          mkdir --parents ./lib/build/outputs/aar
          mv ./releaseAssets/tmpfile-android-release.aar ./lib/build/outputs/aar/

          mkdir --parents ./lib/build/libs
          mv ./releaseAssets/tmpfile-android-*-javadoc.jar ./lib/build/libs/
          mv ./releaseAssets/tmpfile-android-*-sources.jar ./lib/build/libs/

      - name: Upload to Bintray
        run: ./gradlew bintrayUpload -PbintrayUser=${{ secrets.BINTRAY_API_USER }} -PbintrayApiKey=${{ secrets.BINTRAY_API_KEY }}

  versionIncrementer:
    runs-on: ubuntu-18.04
    needs: bintray
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - run: ./doincrementversion

      - name: git commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - Version Incrementer"
          git remote set-url origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

          git add lib/build.gradle README.md sampleapp/app/build.gradle

          if git commit -m "PostRelease version increment"
          then
            git push
          fi

  sampleApp:
    needs: versionIncrementer
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: .github/installAndroidTools.sh

      - run: |
          cd sampleapp
          ./gradlew assembleDebug -PdisablePreDex

      - name: Upload app-debug.apk
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: sampleapp/app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/zip
