name: Publish release

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Download assets from this Release
        uses: ViliusSutkus89/release-asset-downloader@v1.0.2
        with:
          outputDirectory: 'releaseAssets'

      - name: Put release assets where gradle would have kept it after the build
        run: |
          ls -lha ./releaseAssets
          mkdir --parents ./lib/build/outputs/aar
          mv ./releaseAssets/tmpfile-android-release.aar ./lib/build/outputs/aar/

          mkdir --parents ./lib/build/libs
          mv ./releaseAssets/tmpfile-android-*-javadoc.jar ./lib/build/libs/
          mv ./releaseAssets/tmpfile-android-*-sources.jar ./lib/build/libs/

      - name: Upload to Bintray
        run: ./gradlew bintrayUpload -PbintrayUser=${{ secrets.BINTRAY_API_USER }} -PbintrayApiKey=${{ secrets.BINTRAY_API_KEY }}

  incrementVersion:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - run: ./doincrementversion

      - name: Binary committer
        run: |
          if ! git diff-index --quiet HEAD
          then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action - Version Incrementer"

            git remote add github "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
            git pull github "${{ github.ref }}" --ff-only
            git add lib/build.gradle README.md sampleapp/app/build.gradle
            git commit -m "Post release version increment"
            git push github "HEAD:${{ github.ref }}"
          fi

