name: Release build

on: [ push ]

env:
  ANDROID_SDK_TOOLS: "4333796"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Android tools
      run: |
        if test ! -d $ANDROID_HOME/tools/bin/sdkmanager
        then
          wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
          sudo unzip -d $ANDROID_HOME android-sdk.zip > /dev/null
          rm android-sdk.zip
        fi
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "tools" > /dev/null
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null

    - name: Assemble Release
      run: ./gradlew assembleRelease

